# Generated by Django 3.0.3 on 2020-03-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0003_auto_20200319_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profilePic',
            field=models.ImageField(upload_to='userpages'),
        ),
    ]
