# Generated by Django 3.0.3 on 2020-03-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0004_auto_20200319_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='userId',
            new_name='user',
        ),
    ]
