# Generated by Django 3.0.3 on 2020-03-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0005_auto_20200319_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='userpages'),
        ),
    ]
