# Generated by Django 3.0.3 on 2020-03-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0006_auto_20200326_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profilePic',
            field=models.ImageField(default='settings.MEDIA_ROOT/userpages/exit.png', upload_to='userpages'),
        ),
    ]
