# Generated by Django 3.0.3 on 2020-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0007_auto_20200326_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profilePic',
            field=models.ImageField(default='media/userpages/exit.png', upload_to='userpages'),
        ),
    ]
