# Generated by Django 3.0.3 on 2020-03-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0008_auto_20200327_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profilePic',
            field=models.ImageField(default='userpages/exit.png', upload_to='userpages'),
        ),
    ]
