# Generated by Django 3.0.3 on 2020-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0016_auto_20200408_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Kein Titel', max_length=100),
        ),
    ]
