# Generated by Django 3.0.3 on 2020-04-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0017_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='blog',
        ),
    ]
