# Generated by Django 3.0.3 on 2020-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='board',
            field=models.CharField(default='tsldklstbbbbbbbb                                BBBBBBBBTSLDKLST', max_length=64),
        ),
    ]
