# Generated by Django 3.0.3 on 2020-04-19 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess', '0002_auto_20200416_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='moveCounter',
            field=models.IntegerField(auto_created=True, default=0),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='player2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
    ]
