# Generated by Django 3.0.3 on 2020-04-19 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chess', '0003_auto_20200419_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='player2',
            field=models.ForeignKey(default='lukas', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
