# Generated by Django 3.0.3 on 2020-04-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0010_chessgame_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgame',
            name='moveCounter',
        ),
        migrations.RemoveField(
            model_name='chessgame',
            name='player2',
        ),
    ]
