# Generated by Django 3.0.3 on 2020-04-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0011_auto_20200419_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='moveCounter',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
